# Generated by Django 4.1.1 on 2023-01-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='radio',
            field=models.TextField(default='r1'),
        ),
    ]
